server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: job
          uri: http://localhost:8081
          predicates:
            - Path=/jobs/** 
        - id: working
          uri: http://localhost:8082
          predicates:
            - Path=/workings/**,/payings/** 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: jobmanagecenter
          uri: http://localhost:8084
          predicates:
            - Path=/jobInfos/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: job
          uri: http://job:8080
          predicates:
            - Path=/jobs/** 
        - id: working
          uri: http://working:8080
          predicates:
            - Path=/workings/**,/payings/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: jobmanagecenter
          uri: http://jobmanagecenter:8080
          predicates:
            - Path=/jobInfos/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080